library(DT)
library(shiny)
library(shinydashboard)
library(googleVis)
library(leaflet)
library(maps)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(leaflet)
#library(xlsx)

df = read.csv('./suicide.csv', stringsAsFactors = FALSE, fileEncoding="UTF-8-BOM")
# happy1 = read.csv("./2015.csv", stringsAsFactors = FALSE)
# happy2 = read.csv("./2016.csv", stringsAsFactors = FALSE)
# happy3 = read.csv('./2017.csv', stringsAsFactors = FALSE)
#corruption = read.xlsx('./CPI2015.xlsx', sheetIndex = 1, header=TRUE, colClasses=NA)
